theme = "dark_plus"

[editor]
line-number = "relative"
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-q = ":bc"
C-Q = ":bco"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
